### ISSUE TITLE
Did you reverse this or you took it from masterof13fps?

### ISSUE THREAD

**Issue by l0q6** [KamikazeVerde/SlackClient-Deobfuscated#1]

**Comment by KamikazeVerde** [comment]
I did not reverse this but I didn't took it from masterof13fps tho. Qreaj deobfuscated this but he didn't want credits so... This version is actually pretty old (one of the first build ig) and it has meme things such as an AntiVoid for Polar 🤣.

**Comment by KamikazeVerde** [comment]
I did not reverse this but I didn't took it from masterof13fps tho. Qreaj deobfuscated this but he didn't want credits so... This version is actually pretty old (one of the first build ig) and it has meme things such as an AntiVoid for Polar 🤣.
